### ISSUE TITLE
insert hangs

### ISSUE THREAD

**Issue by yurasik2000** [artpaul/clickhouse-cpp#108]
Redirect from here  https://github.com/IMSMWU/RClickhouse/issues/60

> we investigated this issue in more detail. It is related to the Clickhouse-cpp client, which is used in the background. Insert queries seem to return "data" on the wire protocol, which is discarded per default in case of the insert-command (see [1] for details). However, when you use the sendQuery/execute interface directly, it is not discarded, but blocks (the cpp client waits for data which is never received). In consequence, it cannot be directly fixed by us, but it could be targeted by the Clickhouse-cpp colleagues (https://github.com/artpaul/clickhouse-cpp). This behaviour is induced by the use of the dbExecute command for inserts. 

[1] https://github.com/ClickHouse/clickhouse-cpp/blob/a22e075ae7107074cd53181d7a4e8c74c72e23c2/clickhouse/client.cpp#L245

**Comment by artpaul** [comment]
Hi,

This is not a bug. There is no way to execute queries like "INSERT INTO tag_join VALUES (1)"
because the server doesn't parse the VALUES section in case of the raw TCP protocol.

Default command-line client converts values into a block at client-side:
https://github.com/ClickHouse/ClickHouse/blob/master/programs/client/Client.cpp#L825

**Comment by yurasik2000** [comment]
Clear! Thanks!
