### ISSUE TITLE
Little error

### ISSUE THREAD

**Issue by coolpsix** [artpaul/clickhouse-cpp#26]
In implemention of date column:
`data_(std::make_shared<ColumnUInt16>())`
`std::shared_ptr<ColumnUInt32> data_`

**Comment by artpaul** [comment]
Hi! 
Can you give a link to the exact line of code with possible error?

**Comment by coolpsix** [comment]
clickhouse-cpp/clickhouse/columns/date.cpp : 5
 clickhouse-cpp/clickhouse/columns/date.h : 68
Maybe i misuderstood something, because i'm bad at c++, but i think it's misprint.

**Comment by artpaul** [comment]
Everything seems OK, because 

- ColumnUInt32 (https://github.com/artpaul/clickhouse-cpp/blob/master/clickhouse/columns/date.h#L68) are using for storing data for ColumnDateTime which is 32-bit integer in ClickHouse and 
- ColumnUInt16 (https://github.com/artpaul/clickhouse-cpp/blob/master/clickhouse/columns/date.cpp#L7) are using for storing data for ColumnDate which is 16-bit integer.
